# Generated by Django 2.0.3 on 2018-04-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affitti', '0002_auto_20180406_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobile',
            name='condominio',
        ),
        migrations.AddField(
            model_name='condominio',
            name='immobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Immobile'),
        ),
    ]
