# Generated by Django 2.0.3 on 2018-04-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affitti', '0003_auto_20180406_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrattolocazione',
            name='immobile',
        ),
        migrations.AddField(
            model_name='immobile',
            name='contratto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.ContrattoLocazione'),
        ),
    ]
