# Generated by Django 2.0.3 on 2018-04-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affitti', '0004_auto_20180407_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amministratore',
            name='codice_fiscale',
            field=models.CharField(help_text='max_length=16', max_length=16),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='cognome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='indirizzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='nascita_data',
            field=models.DateField(verbose_name='data di nascita'),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='nascita_luogo',
            field=models.CharField(max_length=100, verbose_name='luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='partita_iva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='recapito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Recapito'),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
        migrations.AlterField(
            model_name='amministratore',
            name='societa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Societa', verbose_name='società'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='codice_fiscale',
            field=models.CharField(help_text='max_length=16', max_length=16),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='canone_importo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='canone_periodicita',
            field=models.PositiveSmallIntegerField(help_text='numero mesi '),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='cauzione_importo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='cauzione_modalita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='conduttore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Inquilino'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='contratto_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.ContrattoTipo'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='data_risoluzione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='data_stipula',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='decorrenza',
            field=models.PositiveSmallIntegerField(help_text='numero mesi'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='disdetta_conduttore',
            field=models.PositiveSmallIntegerField(help_text='numero mesi'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='disdetta_locatore',
            field=models.PositiveSmallIntegerField(help_text='numero mesi'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='durata',
            field=models.PositiveSmallIntegerField(help_text='numero mesi'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='locatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Proprietario'),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='modalita_pagamento',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='registrazione_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='registrazione_numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contrattolocazione',
            name='registrazione_ufficio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contrattospesa',
            name='contratto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.ContrattoLocazione'),
        ),
        migrations.AlterField(
            model_name='contrattospesa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattospesa',
            name='importo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contrattotipo',
            name='istat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Istat'),
        ),
        migrations.AlterField(
            model_name='contrattotipo',
            name='iva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Iva'),
        ),
        migrations.AlterField(
            model_name='contrattotipo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='categoria',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='indirizzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='rendita',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='cap',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='comune',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='numero_civico',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='paese',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='toponomia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='codice_fiscale',
            field=models.CharField(help_text='max_length=16', max_length=16),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='cognome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='indirizzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nascita_data',
            field=models.DateField(verbose_name='data di nascita'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nascita_luogo',
            field=models.CharField(max_length=100, verbose_name='luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='partita_iva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='recapito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Recapito'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='societa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Societa', verbose_name='società'),
        ),
        migrations.AlterField(
            model_name='istat',
            name='aliquota',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='iva',
            name='aliquota',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='codice_fiscale',
            field=models.CharField(help_text='max_length=16', max_length=16),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cognome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='indirizzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nascita_data',
            field=models.DateField(verbose_name='data di nascita'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nascita_luogo',
            field=models.CharField(max_length=100, verbose_name='luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='partita_iva',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='recapito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Recapito'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='societa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Societa', verbose_name='società'),
        ),
        migrations.AlterField(
            model_name='societa',
            name='codice_fiscale',
            field=models.CharField(help_text='max_length=16', max_length=16),
        ),
        migrations.AlterField(
            model_name='societa',
            name='indirizzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Indirizzo'),
        ),
        migrations.AlterField(
            model_name='societa',
            name='nome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='societa',
            name='recapito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affitti.Recapito'),
        ),
        migrations.AlterField(
            model_name='societa',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
