# Generated by Django 2.0.3 on 2018-04-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affitti', '0005_auto_20180407_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrattolocazione',
            name='contratto_spesa',
        ),
    ]
